V4 update
iteco-labss/BotX.Api.Core pull request #43
Opened 2021-12-28 14:59 UTC by Vidrochka

2022-01-11 09:05 UTC, ne2poy requested changes

2022-01-11 09:05 UTC, ne2poy commented on src/Examples/Example.ChatProcessing/Bot/ChatMessageAction.cs
> +			await MessageSender.EditMessageAsync(userMessage, syncId, $"You said: {userMessage.Command.Body}", buttons);
А зачем ты тут дважды создаёшь одинаковые кнопки и редактируешь сообщение на тоже самое?

2022-01-11 09:05 UTC, ne2poy commented on src/Examples/Example.ChatProcessing/Bot/ChatMessageAction.cs
> +		}
Тут стоит добавить пример обработки файла, который прилетел от юзера

2022-01-11 09:28 UTC, Vidrochka commented on src/Examples/Example.ChatProcessing/Bot/ChatMessageAction.cs
> +			await MessageSender.EditMessageAsync(userMessage, syncId, $"You said: {userMessage.Command.Body}", buttons);
Чтобы в CountClickPayload лежал id текущего сообщения
До этого можно было самому указать id сообщения, и по этому редактирование не требовалось. Теперь чтобы получить id сообщения его надо сначала отправить

2022-01-11 10:01 UTC, ne2poy commented on src/Examples/Example.ChatProcessing/Bot/ChatMessageAction.cs
> +			await MessageSender.EditMessageAsync(userMessage, syncId, $"You said: {userMessage.Command.Body}", buttons);
ок понял, но кнопки можно дважды не создавать, а юзать одни

2022-01-11 11:53 UTC, Vidrochka commented on src/Examples/Example.ChatProcessing/Bot/ChatMessageAction.cs
> +			await MessageSender.EditMessageAsync(userMessage, syncId, $"You said: {userMessage.Command.Body}", buttons);
Добавил методы редактирования Payload и EventName. Изменил пример для переиспользования кнопок

2022-01-11 13:42 UTC, Vidrochka commented on src/Examples/Example.ChatProcessing/Bot/ChatMessageAction.cs
> +		}
Добавил, попутно актуализировал загрузку файла пользователем

2022-01-12 08:14 UTC, TemaSM commented on src/BotX.Api.Core/BotUI/MessageButton.cs
> +		/// <param name="payload">Дополнительные аргументы, которые будут переданны в метод-обработчик</param>
```suggestion
		/// <param name="payload">Дополнительные аргументы, которые будут переданы в метод-обработчик</param>
```

2022-01-12 08:52 UTC, TemaSM approved these changes

2022-01-12 10:26 UTC, ne2poy commented on src/BotX.Api.Core/JsonModel/Response/Attachment.cs
> +		[JsonProperty("type")]
отступ сломался

2022-01-12 10:27 UTC, ne2poy commented on src/Examples/Example.ChatProcessing/Bot/ChatMessageAction.cs
> +				return;
отступ

2022-01-12 10:27 UTC, ne2poy commented on src/Examples/Example.ChatProcessing/Bot/ChatMessageAction.cs
>  			var buttons = new MessageButtonsGrid();
отступ

2022-01-12 10:31 UTC, ne2poy commented
Если где то ещё увидишь табы, поправь на пробелы плс

2022-01-12 11:47 UTC, ne2poy approved these changes

2022-01-13 07:05 UTC, merged